export const character_type_options = [
    { label: '人类', value: 1 },
    { label: '动物', value: 2 },
]
export const character_gender_options = [
    { label: '男', value: 1 },
    { label: '女', value: 2 },
    { label: '未知', value: 3 },
]
export const character_people_years_old_options = [
    { label: '幼年', value: 1 },
    { label: '青年', value: 2 },
    { label: '中年', value: 3 },
    { label: '老年', value: 4 },
]
export const character_people_body_options = [
    { label: '胖', value: 1 },
    { label: '瘦', value: 2 },
    { label: '中等', value: 3 },
    { label: '肌肉', value: 4 },
]
export const character_eye_color_options = [
    { label: '黑色', value: 'black' },
    { label: '蓝色', value: 'blue' },
    { label: '绿色', value: 'green' },
    { label: '棕色', value: 'brown' },
    { label: '红色', value: 'red' },
    { label: '白色', value: 'white' },
    { label: '紫色', value: 'purple' },
]
export const character_hair_color_options = [
    { label: '黑色', value: 'black' },
    { label: '白色', value: 'white' },
    { label: '蓝色', value: 'blue' },
    { label: '棕色', value: 'brown' },
    { label: '金色', value: 'gold' },
    { label: '红色', value: 'red' },
    { label: '黄色', value: 'yellow' },
    { label: '绿色', value: 'green' },
    { label: '紫色', value: 'purple' },
    { label: '粉色', value: 'pink' },
    { label: '灰色', value: 'gray' },
    { label: '铜橙', value: 'orange' },
]
export const character_hair_style_options = [
    { label: '短发', value: 1 },
    { label: '短卷发', value: 2 },
    { label: '经典底翘', value: 3 },
    { label: '底纹淡刻', value: 4 },
    { label: '光头', value: 5 },
    { label: '底纹深刻', value: 6 },
    { label: '长发', value: 7 },
    { label: '马尾辫', value: 8 },
    { label: '盘发', value: 9 },
    { label: '齐刘海', value: 10 },
    { label: '法式辫', value: 11 },
    { label: '双马尾', value: 12 },
    { label: '寸头', value: 13 },
    { label: '中分', value: 14 },
    { label: '超长发', value: 15 },
    { label: '大波浪', value: 16 },
    { label: '侧扫刘海', value: 17 },
    { label: '眼间头发', value: 18 },
    { label: '呆毛收拢', value: 19 },
    { label: '钻头卷', value: 20 },
    { label: '公主卷', value: 21 },
    { label: '露额头', value: 22 },
    { label: '翼状头发', value: 23 },
]
export const character_cloth_color_options = [
    { label: '黑色', value: 'black' },
    { label: '白色', value: 'white' },
    { label: '蓝色', value: 'blue' },
    { label: '棕色', value: 'brown' },
    { label: '金色', value: 'gold' },
    { label: '红色', value: 'red' },
    { label: '黄色', value: 'yellow' },
    { label: '绿色', value: 'green' },
    { label: '紫色', value: 'purple' },
    { label: '粉色', value: 'pink' },
    { label: '灰色', value: 'gray' },
    { label: '橙色', value: 'orange' }
]
export const character_cloth_style_options = [
    { label: '风衣', value: 1 },
    { label: '夹克', value: 2 },
    { label: '冲锋衣', value: 3 },
    { label: '牛仔外套', value: 4 },
    { label: '开衫', value: 5 },
    { label: '卫衣', value: 6 },
    { label: '皮衣', value: 7 },
    { label: '短袖', value: 8 },
    { label: 'T恤', value: 9 },
    { label: '衬衣', value: 10 },
    { label: '衬衫', value: 11 },
    { label: '毛衣', value: 12 },
    { label: '背心', value: 13 },
    { label: '羽绒服', value: 14 },
    { label: '长裤', value: 15 },
    { label: '短裤', value: 16 },
    { label: '丝袜', value: 17 },
    { label: '长裙', value: 18 },
    { label: '短裙', value: 19 },
    { label: '牛仔裤', value: 20 },
    { label: '西装', value: 21 },
    { label: '工装', value: 22 },
    { label: '校服', value: 23 },
    { label: '中山装', value: 24 },
    { label: '军装', value: 25 },
    { label: '警服', value: 26 },
    { label: '护士服', value: 27 },
    { label: '白大褂', value: 28 },
    { label: '女仆装', value: 29 },
    { label: '泳装', value: 30 },
    { label: '睡衣', value: 31 },
    { label: '旗袍', value: 32 },
    { label: '礼服', value: 33 },
    { label: '皮鞋', value: 34 },
    { label: '运动鞋', value: 35 },
    { label: '高跟鞋', value: 36 },
    { label: '平底鞋', value: 37 },
    { label: '靴子', value: 38 },
    { label: '拖鞋', value: 39 },
    { label: '布鞋', value: 40 },
    { label: '凉鞋', value: 41 },
    { label: '棉鞋', value: 42 },
]
export const character_animal_type_options = [
    { label: '狐狸', value: 1 },
    { label: '狗', value: 2 },
    { label: '狼', value: 3 },
    { label: '马', value: 4 },
    { label: '猫', value: 5 },
    { label: '鸟', value: 6 },
    { label: '狮子', value: 7 },
    { label: '老虎', value: 8 },
    { label: '鹿', value: 9 },
    { label: '兔子', value: 10 },
    { label: '熊', value: 11 },
    { label: '龙', value: 12 },
    { label: '独角兽', value: 13 },
    { label: '凤凰', value: 14 },
    { label: '海豚', value: 15 },
]
export const character_animal_body_options = [
    { label: '消瘦', value: 1 },
    { label: '正常体型', value: 2 },
    { label: '肥胖', value: 3 },
]
export const character_animal_years_old_options = [
    { label: '幼年', value: 1 },
    { label: '成年', value: 2 },
]
export const character_animal_color_options = [
    { label: '黑色', value: 'black' },
    { label: '白色', value: 'white' },
    { label: '蓝色', value: 'blue' },
    { label: '棕色', value: 'brown' },
    { label: '金色', value: 'gold' },
    { label: '红色', value: 'red' },
    { label: '黄色', value: 'yellow' },
    { label: '绿色', value: 'green' },
    { label: '紫色', value: 'purple' },
    { label: '粉色', value: 'pink' },
    { label: '灰色', value: 'gray' },
    { label: '金黄色', value: 'golden_yellow' },
    { label: '橙色', value: 'orange' },
]